"""Character Profile: structured observation of reference images.

Generated by the host Agent from visual understanding, not by an external
vision API. Only records observable features; uncertain traits are marked
as unknown rather than guessed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class CharacterProfile:
    character_id: str
    display_name: Optional[str] = None
    source_refs: List[str] = field(default_factory=list)
    coat_color: str = ""
    coat_pattern: str = ""
    eye_color: str = ""
    hair_length: str = ""
    body_type: str = ""
    face_shape: str = ""
    distinctive_markings: List[str] = field(default_factory=list)
    accessories: List[str] = field(default_factory=list)
    preserve: List[str] = field(default_factory=list)
    avoid: List[str] = field(default_factory=list)
    uncertain_features: List[str] = field(default_factory=list)
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "character_id": self.character_id,
            "display_name": self.display_name,
            "source_refs": self.source_refs,
            "observable_features": {
                "coat_color": self.coat_color,
                "coat_pattern": self.coat_pattern,
                "eye_color": self.eye_color,
                "hair_length": self.hair_length,
                "body_type": self.body_type,
                "face_shape": self.face_shape,
                "distinctive_markings": self.distinctive_markings,
                "accessories": self.accessories,
            },
            "identity_constraints": {
                "preserve": self.preserve,
                "avoid": self.avoid,
            },
            "uncertain_features": self.uncertain_features,
            "notes": self.notes,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "CharacterProfile":
        obs = data.get("observable_features", {})
        cons = data.get("identity_constraints", {})
        return cls(
            character_id=data["character_id"],
            display_name=data.get("display_name"),
            source_refs=data.get("source_refs", []),
            coat_color=obs.get("coat_color", ""),
            coat_pattern=obs.get("coat_pattern", ""),
            eye_color=obs.get("eye_color", ""),
            hair_length=obs.get("hair_length", ""),
            body_type=obs.get("body_type", ""),
            face_shape=obs.get("face_shape", ""),
            distinctive_markings=obs.get("distinctive_markings", []),
            accessories=obs.get("accessories", []),
            preserve=cons.get("preserve", []),
            avoid=cons.get("avoid", []),
            uncertain_features=data.get("uncertain_features", []),
            notes=data.get("notes", ""),
        )
