"""Character Profile: structured observation of reference images.

Generated by the host Agent from visual understanding, not by an external
vision API. Only records observable features; uncertain traits are marked
as unknown rather than guessed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class CharacterProfile:
    character_id: str
    display_name: Optional[str] = None
    source_refs: List[str] = field(default_factory=list)
    coat_color: str = ""
    coat_pattern: str = ""
    eye_color: str = ""
    hair_length: str = ""
    body_type: str = ""
    face_shape: str = ""
    distinctive_markings: List[str] = field(default_factory=list)
    accessories: List[str] = field(default_factory=list)
    preserve: List[str] = field(default_factory=list)
    avoid: List[str] = field(default_factory=list)
    uncertain_features: List[str] = field(default_factory=list)
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "character_id": self.character_id,
            "display_name": self.display_name,
            "source_refs": self.source_refs,
            "observable_features": {
                "coat_color": self.coat_color,
                "coat_pattern": self.coat_pattern,
                "eye_color": self.eye_color,
                "hair_length": self.hair_length,
                "body_type": self.body_type,
                "face_shape": self.face_shape,
                "distinctive_markings": self.distinctive_markings,
                "accessories": self.accessories,
            },
            "identity_constraints": {
                "preserve": self.preserve,
                "avoid": self.avoid,
            },
            "uncertain_features": self.uncertain_features,
            "notes": self.notes,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "CharacterProfile":
        obs = data.get("observable_features", {}) or {}
        cons = data.get("identity_constraints", {}) or {}

        def pick(key: str, default=""):
            """Prefer nested observable_features, then flat top-level."""
            if key in obs:
                return obs[key]
            return data.get(key, default)

        def pick_list(key: str, default=None):
            default = default or []
            if key in obs:
                return obs[key]
            if key in cons:
                return cons[key]
            return data.get(key, default)

        cid = data.get("character_id")
        if not cid or not isinstance(cid, str):
            raise ValueError("invalid_input: character_id is required and must be a string")

        return cls(
            character_id=cid,
            display_name=data.get("display_name"),
            source_refs=data.get("source_refs", []),
            coat_color=pick("coat_color"),
            coat_pattern=pick("coat_pattern"),
            eye_color=pick("eye_color"),
            hair_length=pick("hair_length"),
            body_type=pick("body_type"),
            face_shape=pick("face_shape"),
            distinctive_markings=pick_list("distinctive_markings"),
            accessories=pick_list("accessories"),
            preserve=pick_list("preserve"),
            avoid=pick_list("avoid"),
            uncertain_features=data.get("uncertain_features", []),
            notes=data.get("notes", ""),
        )
